version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
      POSTGRES_DB: company-event
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - company-events-network

  backend-company-events:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-company-events
    ports:
      - "3005:3005"
    environment:
      POSTGRES_DB_URL: ${POSTGRES_DB_URL}
      POSTGRES_DB_USER: ${POSTGRES_DB_USER}
      POSTGRES_DB_PASSWORD: ${POSTGRES_DB_PASSWORD}
      SHOW_SQL: "true"
      TELEGRAM_BOT_API_ADDRESS: http://company-events-telegram-bot:8081
    depends_on:
      - postgres
    networks:
      - company-events-network

  company-events-telegram-bot:
    build:
      context: ./telegramBot
      dockerfile: Dockerfile
    container_name: company-events-telegram-bot
    ports:
      - "8081:8081"
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      VPS_HOST: ${VPS_HOST}
      BACKEND_API_URL: http://backend-company-events:3005
    depends_on:
      - backend-company-events
    networks:
      - company-events-network

volumes:
  postgres_data:

networks:
  company-events-network:
    driver: bridge
